export default {
  COLOR_MAIN_PURPLE: "#c896e4",
  COLOR_MAIN_MIDDLE: "#ccc8e5",
  COLOR_MAIN_SKYBLUE: "#adc1ed",

  COLOR_WHITE_BACKGROUND: "#ffffff",
  COLOR_GRAY_BACKGROUND: "#AEAEAE",

  COLOR_RECORD_DARK: "#000",
  COLOR_RECORD_LIGHT: "#535353",
  COLOR_RECORD_CIRCLE: "#e9e9e9",
  COLOR_RECORD_LINE: "#4a4a4a",

  COLOR_TRANSPARENT_WHITE: "rgba(255, 255, 255, 0.3)",

  COLOR_WHITE_BORDER: "#ffffff",
  COLOR_GRAY_BORDER: "#AEAEAE",

  COLOR_GRAY_TEXT: "#7D7D7D",

  COLOR_BLUE_AUTH_BUTTON: "#6741ff",
  COLOR_LIGHT_GRAY_PLACEHOLDER: "#acacac",
  COLOR_BLUE_REQUIRED: "#2d65f7",
  COLOR_RED_INVALID: "#e61d1c",
  COLOR_GREEN_VALID: "#0fc20b",
  COLOR_GRAY_INACTIVE_BUTTON: "#bdbdbd",
  COLOR_GRAY_INACTIVE_INPUT: "#e8e8e8",
};
