export default {
  COLOR_MAIN: "#6741FF",

  COLOR_MAIN_PURPLE: "#c896e4",
  COLOR_MAIN_MIDDLE: "#ccc8e5",
  COLOR_MAIN_SKYBLUE: "#adc1ed",

  COLOR_WHITE_BACKGROUND: "#ffffff",
  COLOR_GRAY_BACKGROUND: "#AEAEAE",
  COLOR_LIGHTGRAY_BACKGROUND: "#C6C6C6",

  COLOR_RECORD_DARK: "#000",
  COLOR_RECORD_LIGHT: "#535353",
  COLOR_RECORD_CIRCLE: "#e9e9e9",
  COLOR_RECORD_LINE: "#4a4a4a",

  COLOR_TRANSPARENT_WHITE: "rgba(255, 255, 255, 0.3)",

  COLOR_WHITE_BORDER: "#ffffff",
  COLOR_GRAY_BORDER: "#C5C5C5",
  COLOR_LIGHTGRAY_BORDER: "#DCDCDC",

  COLOR_GRAY_TEXT: "#959595",
  COLOR_DARKGRAY_TEXT: "#4e4e4e",
  COLOR_PINK_TEXT: "#FF66B2",

  COLOR_BLUE_AUTH_BUTTON: "#6741ff",
  COLOR_LIGHT_GRAY_PLACEHOLDER: "#acacac",
  COLOR_BLUE_REQUIRED: "#2d65f7",
  COLOR_RED_INVALID: "#e61d1c",
  COLOR_GREEN_VALID: "#0fc20b",
  COLOR_GRAY_INACTIVE_BUTTON: "#bdbdbd",
  COLOR_GRAY_INACTIVE_INPUT: "#e8e8e8",

  COLOR_STAR: "#4DF64D",
  COLOR_STAR_BACKGROUND: "#CACACA",

  COLOR_MALE: "#2D65F7",
  COLOR_FEMALE: "#F874EB",

  COLOR_FOOTER: "#ECECEC",

  COLOR_GRAY_ICON: "#8d8d8d",

  COLOR_GRADIENT_PURPLE: "#5033FF",
  COLOR_GRADIENT_PINK: "#FFA1F6",

  COLOR_BOX_SHADOW_COLOR: "rgba(217, 217, 217, 0.7)",

  COLOR_LINE_BLUE: "#5033FF",

  COLOR_YOUTUBE_RED: "#ff0000",
  COLOR_RECOMMEND_LABEL: "#efefef",
};
