export default {
  COLOR_MAIN_PURPLE: "#c896e4",
  COLOR_MAIN_MIDDLE: "#ccc8e5",
  COLOR_MAIN_SKYBLUE: "#adc1ed",

  COLOR_WHITE_BACKGROUND: "#ffffff",

  COLOR_RECORD_DARK: "#000",
  COLOR_RECORD_LIGHT: "#535353",
  COLOR_RECORD_CIRCLE: "#e9e9e9",
  COLOR_RECORD_LINE: "#4a4a4a",

  COLOR_TRANSPARENT_WHITE: "rgba(255, 255, 255, 0.3)",
};
